@extends('user.layout.app')
@section('page_name', 'Help')
@section('content')

    <div class="container-fluid px-xl-5 help-section">
        page 1/4
        DISCLAIMER
        Updated at February 19th, 2024
        siostore hereby grants you access to www.siostore.eu (“the Website”) and invites you to purchase the
        services offered here.
        Definitions and key terms
        To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced,
        are strictly defined as:
        l Cookie: small amount of data generated by a website and saved by your web browser. It is used to
        identify your browser, provide analytics, remember information about you such as your language
        preference or login information.
        l Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to SIOPAY
        MULTISERVIZI SRL, PIAZZA PORCELLI SNC 88046 LAMEZIA TERME CZ ITALY that is responsible
        for your information under this Disclaimer.
        l Service: refers to the service provided by siostore as described in the relative terms (if available) and on
        this platform.
        l You: a person or entity that is registered with siostore to use the Services.
        This Disclaimer was created with Termify.
        Limited liability
        siostore endeavours to update and/or supplement the content of the website/app on a regular basis. Despite
        our care and attention, content may be incomplete and/or incorrect.
        The materials offered on the website/app are offered without any form of guarantee or claim to their
        correctness. These materials can be changed at any time without prior notice from siostore.
        Particularly, all prices on the website/app are stated subject to typing and programming errors. No liability is
        assumed for the implications of such errors. No agreement is concluded on the basis of such errors.
        siostore shall not bear any liability for hyperlinks to websites or services of third parties included on the
        website/app. From our website/app, you can visit other websites by following hyperlinks to such external
        sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the
        content and nature of these sites. These links to other websites do not imply a recommendation for all the
        content found on these sites. Site owners and content may change without notice and may occur before we
        have the opportunity to remove a link which may have gone ‘bad’.
        Please be also aware that when you leave our website/app, other sites may have different privacy policies
        and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well
        as their "Terms of Service" before engaging in any business or uploading any information.
        Links to Other Websites Disclaimer
        page 2/4
        This Disclaimer applies only to the Services. The Services may contain links to other websites not operated
        or controlled by siostore. We are not responsible for the content, accuracy or opinions expressed in such
        websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.
        Please remember that when you use a link to go from the Services to another website, our Privacy Policy is
        no longer in effect. Your browsing and interaction on any other website, including those that have a link on
        our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies
        or other methods to collect information about you. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy and Terms of every site You visit.
        We have no control over and assume no responsibility for the content, privacy policies or practices of any
        third party sites or services.
        Errors and Omissions Disclaimer
        siostore is not responsible for any content, code or any other imprecision.
        siostore does not provide warranties or guarantees.
        In no event shall siostore be liable for any special, direct, indirect, consequential, or incidental damages or
        any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in
        connection with the use of the Service or the contents of the Service. siostore reserves the right to make
        additions, deletions, or modifications to the contents on the Service at any time without prior notice.
        General Disclaimer
        The siostore Service and its contents are provided "as is" and "as available" without any warranty or
        representations of any kind, whether express or implied. siostore is a distributor and not a publisher of the
        content supplied by third parties; as such, siostore exercises no editorial control over such content and
        makes no warranty or representation as to the accuracy, reliability or currency of any information, content,
        service or merchandise provided through or accessible via the siostore Service. Without limiting the
        foregoing, siostore specifically disclaims all warranties and representations in any content transmitted on or
        in connection with the siostore Service or on sites that may appear as links on the siostore Service, or in the
        products provided as a part of, or otherwise in connection with, the siostore Service, including without
        limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party
        rights. No oral advice or written information given by siostore or any of its affiliates, employees, officers,
        directors, agents, or the like will create a warranty. Price and availability information is subject to change
        without notice. Without limiting the foregoing, siostore does not warrant that the siostore Service will be
        uninterrupted, uncorrupted, timely, or error-free.
        Copyright Disclaimer
        All intellectual property rights concerning these materials are vested in siostore. Copying, distribution and
        any other use of these materials is not permitted without the written permission of siostore, except and only
        to the extent otherwise provided in regulations of mandatory law (such as the right to quote), unless
        otherwise stated for certain materials.
        Affiliate Links Disclosure
        siostore has affiliate links and in this section of the Disclaimer we will address how we use those affiliate links
        from other websites/companies and products. These “affiliate links” are specific URLs that contain the
        affiliate's ID or username.
        page 3/4
        In compliance with the FTC guidelines, please assume the following about links and posts on this site:
        l Any/all of the links on siostore are affiliate links of which we receive a small commission from sales of
        certain items, but the price is the same for you. As siostore has grown, so have costs associated with
        running and maintaining it, and affiliate links are a way we help offset these costs.
        l If we post an affiliate link to a product, it is something that we personally use, support and would
        recommend without an affiliate link.
        l Unless otherwise noted, all reviews are of items we have purchased and we are not paid or
        compensated in any way.
        We might participate in affiliate programs such as:
        l Amazon Associates Program
        l Ebay Partner Network
        l Others
        Testimonials Disclosure
        Any testimonials provided on this platform are opinions of those providing them. The information provided in
        the testimonials is not to be relied upon to predict results in your specific situation. The results you
        experience will be dependent on many factors including but not limited to your level of personal
        responsibility, commitment, and abilities, in addition to those factors that you and/or siostore may not be able
        to anticipate.
        We will give honest testimonials to our visitors regardless of any discount. Any product or service that we test
        are individual experiences, reflecting real life experiences. The testimonials could be displayed on audio, text
        or video and are not necessarily representative of all of those who will use our products and/or services.
        siostore does not guarantee the same results as the testimonials given on our platform. Testimonials
        presented on siostore are applicable to the individuals writing them, and may not be indicative of future
        success of any other individuals.
        Please don’t hesitate to contact us if you would like to know more about testimonials, discounts, or any of the
        products/services that we review.
        Your Consent
        We've updated our Disclaimer to provide you with complete transparency into what is being set when you
        visit our site and how it's being used. By using our website/app, registering an account, or making a
        purchase, you hereby consent to our Disclaimer and agree to its terms.
        Changes To Our Disclaimer
        Should we update, amend or make any changes to this document so that they accurately reflect our Service
        and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you
        continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this
        or any updated Disclaimer, you can delete your account.
        Contact Us
        Don't hesitate to contact us if you have any questions regarding this Disclaimer.
        page 4/4
        l Via Email: info@siostore.eu
        l Via Phone Number: +3909681916024
        l Via this Link: https://siostore.eu/contact
        l Via this Address: Piazza Porcelli, Lamezia Terme, CZ, Italia
        Powered by TCPDF (www.tcpdf.org)
    </div>

@endsection
@section('scripts')

@endsection
